name: Publish Extractor

on: 
  pull_request:
    branches:
      - "main"
    # inputs:
    #   release_message:
    #     type: string
    #     description: Release message
    #     required: true

jobs:
  detect-extractors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install ./extractor-sdk

